### ISSUE TITLE
VW_NFR_Rascunho_Det - DT_ULT_ATUALIZACAO

### ISSUE THREAD

**Issue by marcusmsv** [marcusmsv/Nova#342]
Fabio,

Existe a possibilidade de incluir o campo DT_ULT_ATUALIZACAO na view VW_NRF_Rascunho_Det?

Obrigado

**Comment by fabioInfor** [comment]
Marcus,

Criei o campo DT_ATUALIZACAO.

**Comment by marcusmsv** [comment]
Concluído.
