### ISSUE TITLE
VW_TRP_ANALITICO/Atualiza - DT_ULT_ATUALIZACAO

### ISSUE THREAD

**Issue by marcusmsv** [marcusmsv/Nova#343]
Fabio,

Poderia verificar a possibilidade de criar um campo com a Data da Ultima Atualização na view VW_TRP_ANALITICO.
VW_TRP_Analitico_Atualiza

Obrigado.

**Comment by fabioInfor** [comment]
Marcus,

Criei o campo DT_ATUALIZACAO nas duas views.

**Comment by marcusmsv** [comment]
Concluído.
