### ISSUE TITLE
VW_CAR_Titulo_Mvmt - NR_TITULO_REFERENCIA

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#344]
Fábio

Conferindo os dados extraídos com o LN, encontrei um problema com esse campo e precisamos que você reveja a programação do mesmo.

o documento "RB3 108" tem como CD_TRANSACAO_DOCUMENTO e NR_MOVIMENTO: "RGL 177", "RGL 178" e "RGL 180" e como NR_TITULO_REFERENCIA "RG 324", "RGN 121" e "RG 325", respectivamente.

Consultando pelo LN, o "RG 324" é apresentado para o "RGL 179", mas a view está mostrando como resultado o "RGL 177". Veja a imagem:

![image](https://cloud.githubusercontent.com/assets/7606062/6042414/b8021cda-ac6b-11e4-91b7-d14d1a30f9c2.png)

Fico no aguardo de sua resposta.

**Comment by fabioInfor** [comment]
Rosana,

O título RG3-24 está agrupando o  RB3-108, veja abaixo:

![image](https://cloud.githubusercontent.com/assets/7606647/6043382/f642f03a-ac72-11e4-83e7-9cf7de1aef1d.png)

**Comment by rosanaprignolato** [comment]
Ok Fábio, já fiz o mapeamento de conferência no arquivo.
