### ISSUE TITLE
VW_EST_ESTOQUE - Campo QT_RESERVADA

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#346]
Humberto, estou conferindo os dados extraídos pela View com as telas do LN. 

Para a variável "QT_RESERVADA" , a view não está trazendo os dados da ordem de Venda "V20000487", porém essa ordem existe na tela do LN (sessão whinp1500m000 - Transações de Inventário Planejado).

Você poderia verificar e me explicar o motivo?

**Comment by rosanaprignolato** [comment]
A view do LN para o Tipo de Bloqueio “WN” está considerando os registros da tabela baandb.twhinp100201 com as seguintes restrições:

Where a.t$koor = 3  	  --ordem de venda
                and a.t$kotr = 2  	  --baixa planejada
                and a.t$cdis$c = ' '   --restrição (Tp Bloqueio)

Acontece que na tela que usamos para pegar os dados (Sessão whinp1500m000 - Transações de Inventário Planejado) esse campo de restrição não aparece. O caso da ordem “V20000487” mencionada é exatamente por esse motivo, pois a mesma tem a informação “WR” neste campo.

Sem a existência deste campo, mesmo que oculto para futura seleção, não consigo validar os dados via tela do LN.

Fábio, tem algum outro caminho para fazermos essa validação?

**Comment by fabioInfor** [comment]
Rosana,

Este campo só existe na tabela mesmo, seria necessário abrir um chamado para customização da tela de transações de inventário para mostrar este campo.
