### ISSUE TITLE
VW_EST_ESTOQUE

### ISSUE THREAD

**Issue by marcusmsv** [marcusmsv/Nova#347]
Bom dia Humberto/Fabio,

Na ultima semana modificamos a view de Estoque para atender a necessidade de estoque que estava retornando nulo, que segundo o Fabio identificou, era problemas ocasionados por regra de calculo.

No entanto, temos um chamado na fila do MIS, de saldo de estoque com valores negativos do LN.

Poderiam verificar.

Segue caso para teste:

select * from VW_EST_ESTOQUE where qt_saldo < 0

select * from VW_EST_ESTOQUE where qt_saldo < 0
and cd_item in (1736243,1723384)

Qualquer dúvida, me avisem.

Obrigado

**Comment by fabioInfor** [comment]
Marcus,

Eu verifiquei e o Humberto fez uma alteração para mostrar "zero" onde o valor estava negativo. Voce chegou a verificar se o problema persiste?

**Comment by marcusmsv** [comment]
Resolvido.
