### ISSUE TITLE
VW_NFR_DET

### ISSUE THREAD

**Issue by marcusmsv** [marcusmsv/Nova#351]
Fabio,

Poderia verificar se os casos resultantes da query abaixo são dados de Testes ou se foram casos reais no ambiente de homologação (201), pois este atributo se refere a quantidade física recebida do pedido, e o valor zerado para este atributo nos deixou com esta dúvida.

select * from vw_nfr_det where QT_RECEBIDA_FISICA =0

Obrigado.

**Comment by hkasai** [comment]
Marcus,

Verifiquei que a maioria das notas que tem a quantidade física recebida igual a zero estão aguardando o retorno do WMS. Sem o retorno do WMS, o Ln não cria o número de recebimento físico na tabela "tdrec947", onde, por este, acessa a tabela "whinh312".
Não sei se esta era a dúvida, mas estou à disposição para maiores esclarecimentos.

Grato, Humberto.

**Comment by marcusmsv** [comment]
Humberto,

Conseguimos incluir o status do item na NFR_DET, para sabermos se houve ou não o recebimento fisico? Com este atributo, conseguimos filtrar os dados nos nosso processos que precisam ler apenas os dados de recebimento que houve o recebimento físico.

Obrigado.

**Comment by hkasai** [comment]
Marcus,

Podemos incluir o campo Status NF, "tdrec940.stat.l", onde você poderá filtrar os status 4 e 5, "Aprovado" e "Aprovado com Problemas". Só neste momento o recebimento físico é criado.

Grato, Humberto.

**Comment by marcusmsv** [comment]
Humberto,

Poderia incluir a coluna CD_STATUS_NF com estes dados?

Qual seria o que esta com a quantidade zerada?

Obrigado.

**Comment by hkasai** [comment]
Marcus,

Vou incluir o código e a descrição do status.

No ambiente de Homologação, a maioria dos registros zerados está com status 200 (Aguardando WMS) e 201 (Pronto para envio ao WMS). Há casos com status 4 e 5, mas segundo o Antunes, está errado, pois não se pode aprovar uma nota sem retorno do WMS. Ele comentou que não há casos na Produção, mas não executei a query lá.

Grato, Humberto.

**Comment by marcusmsv** [comment]
Humberto,

Executei a query em produção (301) e retornam dados com valores zerados!

**Comment by hkasai** [comment]
Marcus,

Atualizei a query no Github, incluindo os campos de Status_NF e Desc_Status. 
Na Produção não podemos ter casos de notas aprovadas, status 4 e 5, com recebimento físico zerado. Caso isto ocorra, teremos que passar os casos aos consultores de Ln.

Grato, Humberto.
