### ISSUE TITLE
VW_NFV_CAB - Tempo Execução

### ISSUE THREAD

**Issue by marcusmsv** [marcusmsv/Nova#352]
Fabio,

Conforme verificamos, a Query de nota cabeçalho se torna lenta em sua execução por conta da extração da ultima modificação nas tabelas linha e imposto da Nota.

Como alternativa, foi sugerido que para este caso, utilizarmos a data da emissão da NF, tendo em vista o prazo Sefaz de cancelamento ou modificação da Nota.

Abaixo , seguem alguns casos que fogem do range de 1 dia de diferença entre emissão e modificação da NF.

Poderia verificar qual evento que causou a modificação das referencias.

000015068 - 101 Dias
000011108 - 85 Dias
000016265 - 33 Dias
000013115 - 28 Dias
000017255 - 27 Dias
000010048 - 21 Dias
000018537 - 20 Dias
000031358 - 18 Dias
000032186 - 16 Dias
000022405 - 7 Dias

Obrigado.

**Comment by marcusmsv** [comment]
Fabio,

Conforme avaliamos, poderia incluir o campo "NR_REFERENCIA_FISCAL_FAT"  na view VW_NFV_CAB  para que na situação de Referencia Fiscal de fatura, conseguimos identificar a remessa através deste campo?

Obrigado.

**Comment by fabioInfor** [comment]
Marcus,

Campo criado;

**Comment by fabioInfor** [comment]
Marcus,

Campo criado;

**Comment by fabioInfor** [comment]
Marcus,

Campo criado

**Comment by marcusmsv** [comment]
Conforme verificado, esta view foi modificada para filtrar os dados pela Data da Emissão.
