### ISSUE TITLE
Criação View Módulo Despesas

### ISSUE THREAD

**Issue by marcusmsv** [marcusmsv/Nova#353]
Fabio,

Poderia desenvolver as views listadas abaixo com base na dimensão que verificamos:

VW_DOM_FILIAL_LN
VW_DOM_UNIDADE_NEGOCIO_LN
VW_DOM_BANDEIRA
VW_DOM_PROJETO

Obrigado.

**Comment by marcusmsv** [comment]
Fabio,

Para todas as views, pode selecionar todos os campos que estão na tela do LN, que elimino aqui quais não formos usar!

Obrigado.

**Comment by fabioInfor** [comment]
Queries criadas

**Comment by marcusmsv** [comment]
Views Criadas
