### ISSUE TITLE
VW_GAR_ESTENDIDA - Validação

### ISSUE THREAD

**Issue by marcusmsv** [marcusmsv/Nova#354]
Fabio,

Poderia verificar se esta view esta retornando todas as garantias, ou somente as canceladas ou somente as não canceladas.

Obrigado.

**Comment by fabioInfor** [comment]
Marcus e Rosana,

Eu não encontrei nenhum exemplo de garantia estendida cancelada,mas verifiquei na query e aparentemente a condição está errada. Da forma que está hoje 1 significa que a garantia "Não está cancelada" e 2 "Cancelada". Talvez isso deva ser invertido, O que voce acha?

**Comment by marcusmsv** [comment]
Fabio,

Consegue colocar um case para:

Quando cancelada = 1
Quando não cancelada = 0

Obrigado.

**Comment by fabioInfor** [comment]
Condição alterada conforme solicitado.

**Comment by marcusmsv** [comment]
Concluído.
