### ISSUE TITLE
VW_NFR_CAB - Inclusão Coluna

### ISSUE THREAD

**Issue by marcusmsv** [marcusmsv/Nova#355]
Fabio,

Conforme conversamos, poderia incluir na view de recebimento, os campos, com base nos prints anexo:

NR_NF_DEVOLUCAO
NR_SERIE_NF_DEVOLUCAO

![titulocap](https://cloud.githubusercontent.com/assets/7514619/6450672/2e6c79dc-c108-11e4-8291-8f75ab68748f.jpg)

**Comment by fabioInfor** [comment]
Foram adicionadas as colunas solicitadas.

**Comment by marcusmsv** [comment]
Fabio,

Conforme alinhamos, precisamos que o numero da nota e série de devolução, seja carregada na linha de detalha.

Pode utilizar a Referencia Fiscal R00003515 como exemplo. Ela foi gerada pela nota de recebimento final 3503.

Qualquer dúvida, me avise!

**Comment by fabioInfor** [comment]
Marcus,

Foi incluído o numero da nota e serie conforme falamos.

**Comment by fabioInfor** [comment]
Marcus,

Alterei a NFR_Cab conforme conversamos.

**Comment by marcusmsv** [comment]
Fabio,

Conforme avaliamos, poderia incluir nos campos NR_NF_RECEBIDA e NR_SERIE_NF_RECEBIDA o valor da NF gerada no LN pela devolução, e não a NF de recebimento, pois com o NR_NFR ja temos o lastro com a nota principal.

Obrigado.

**Comment by fabioInfor** [comment]
Query alterada, favor validar.

**Comment by marcusmsv** [comment]
Concluido.
