### ISSUE TITLE
VW_DES_RAZAO_CONTABIL - Validação

### ISSUE THREAD

**Issue by marcusmsv** [marcusmsv/Nova#357]
Fabio,

Tem uma view que criei no repositório do Github chamada VW_DES_RAZAO_CONTABIL.

Essa view deverá atender um processo do MIS para despesas.

Contudo, ela não possui o o numero do titulo gerado pela despesa.

Poderia verificar se é possível inserir com base na query da view?

Obrigado.

**Comment by fabioInfor** [comment]
Marcus,

Inclui o numero de documento e linha, que fazem parte do índice da tabela de lançamentos contábeis, desta maneira não deve duplicar. Veja abaixo tela do LN com informações que foram adicionadas:


![image](https://cloud.githubusercontent.com/assets/7606647/6493628/ba31a634-c29a-11e4-9193-582d6c1bfa80.png)

**Comment by marcusmsv** [comment]
Resolvido
