### ISSUE TITLE
VW_DOM_TIPO_TRANSACAO_RAZAO

### ISSUE THREAD

**Issue by marcusmsv** [marcusmsv/Nova#358]
Fabio,

Poderia gerar uma view de domínio para os registros da coluna TIPO_TRANSACAO da view VW_DES_RAZAO_CONTABIL.

Obrigado.

**Comment by fabioInfor** [comment]
Marcus,

View criada, porem já existia a VW_DOM_Transacao que tinha esta informação e mais alguns campos, talvez seja possível unificar.

**Comment by marcusmsv** [comment]
Resolvido
