### ISSUE TITLE
VW_NFR_CAB - Filial Vazia

### ISSUE THREAD

**Issue by marcusmsv** [marcusmsv/Nova#359]
Bom dia Fabio,

Poderia verificar as referencias printadas abaixo, o motivo pelo qual esta sendo carregada com Filial vazia?

Obrigado.
![filialnull](https://cloud.githubusercontent.com/assets/7514619/6555830/a9ab4b34-c647-11e4-92ec-e953c9b4137f.jpg)

**Comment by fabioInfor** [comment]
Marcus,

Isto acontece poorque o campo "Cat. Uni. Empresarial" está em branco para unidade empresarial dessas referencias fiscais. Nós já conversamos sobre este problema outro dia e voce falou de substituir pelo código da unidade empresarial. Veja telas abaixo:

![image](https://cloud.githubusercontent.com/assets/7606647/6556586/3be8785a-c64d-11e4-8591-dcd833173bda.png)

**Comment by marcusmsv** [comment]
Resolvido
