### ISSUE TITLE
VW_CAP_TITULO - Alteração

### ISSUE THREAD

**Issue by marcusmsv** [marcusmsv/Nova#360]
Fabio,

Conforme conversamos, na view CAP_TITULO, esta ocorrendo o mesmo cenário da VW_NFR_CAB para notas e séries de notas de devolução gerada no LN.

Poderia ajustar essa view para nos casos de devolução, a linha do titulo retorne a nota e série da nota de devolução, ao invés da nota e série da nota de recebimento?

Obrigado.

**Comment by fabioInfor** [comment]
Marcus,

Fiz a alteração para mostrar os dados da nota fiscal de devolução, favor validar.

**Comment by marcusmsv** [comment]
Resolvido
