### ISSUE TITLE
VW_NFV_Eletronica - Tempo Execução

### ISSUE THREAD

**Issue by marcusmsv** [marcusmsv/Nova#361]
Fabio,

Poderia verificar a view de nota fiscal eletronica. Não estou conseguindo executar ela no ambiente da 201.

Obrigado.

**Comment by fabioInfor** [comment]
Marcus,

Fiz algumas alterações e aparentemente ficou mais rápido, favor verificar.

**Comment by marcusmsv** [comment]
Fabio,

O tempo de execução foi melhor na versão alterada
