### ISSUE TITLE
VW_CAR_Retorno_Cobr_Eletr - ORA-01722

### ISSUE THREAD

**Issue by marcusmsv** [marcusmsv/Nova#363]
Fabio,

Poderia verificar o erro que teve inicio hoje na view de retorno de cobrança eletronica.

Obrigado.

**Comment by fabioInfor** [comment]
Tinha uma condição que estava relacionando um campo string com numero, fiz a correção.

**Comment by marcusmsv** [comment]
Fabio,

Ainda com problema nessa view!

Poderia verificar?

Obrigado.

**Comment by fabioInfor** [comment]
Marcus,

A tabela usada nessa query não tem dados, então não retorna nenhuma linha, executei a query agora e não apresentou nenhum erro.


![image](https://cloud.githubusercontent.com/assets/7606647/7187901/69835cf6-e44a-11e4-8534-32a4e2752074.png)

**Comment by marcusmsv** [comment]
Fabio,

Estou com o seguinte erro ao executar a consulta:

![image](https://cloud.githubusercontent.com/assets/7514619/7188028/38b5caa4-e44b-11e4-9657-9c3ccaedc122.png)

**Comment by fabioInfor** [comment]
Pode enviar a query desta view? não tenho aceso a view e executando a query "VW_CAR_Retorno_Cobranca_Eletronica.sql" o erro não acontece.
