### ISSUE TITLE
VW_DEV_DEVOLUCAO - Duplicidade

### ISSUE THREAD

**Issue by marcusmsv** [marcusmsv/Nova#364]
Fabio,

Identifiquei um caso de devolução que tem mais de uma entrega, com duas notas de remessas diferentes, porem com o mesmo numero de referencia fiscal, esta correto?

Poderia verificar se é caso de teste, ou se haverá casos de devolução com duas entregas sob o mesmo numero de referencia fiscal?

Obrigado.

**Comment by fabioInfor** [comment]
Marcus,

Não é para acontecer isto, porem eu procurei um caso na VW_DEV_Devolução, onde o campo NR_NFR_DEVOLUCAO tenha mais de um valor distinto para o campo NR_ENTREGA_DEVOLUCAO e não encontrei. Poderia por favor, enviar o exemplo que voce encontrou o problema?

**Comment by marcusmsv** [comment]
Fabio,

Segue referencia fiscal identificada: F20007226

**Comment by fabioInfor** [comment]
Marcus,

Nesse exemplo foi feita uma venda com dois itens (que gerou a ref. fiscal F20007226), depois de faturado foram geradas duas devoluções (uma para cada item). Acho que isto pode acontecer sim, já que as devoluções podem ser feitas em momentos diferente, o que não poderia é ter mais de uma entre relacionada a uma NF de devolução.

Veja abaixo que temos uma entrega de venda e duas de devolução.

![image](https://cloud.githubusercontent.com/assets/7606647/6849096/b31a6dd8-d3af-11e4-8702-cafb2667252e.png)

**Comment by marcusmsv** [comment]
Fabio,

Poderia ver este caso?

NR_REFERENCIA_FISCAL_FATURA = 'F20027410'

**Comment by fabioInfor** [comment]
Marcus,

Atualizei a query conforme falamos.

**Comment by marcusmsv** [comment]
Resolvido.
