### ISSUE TITLE
VW_PEV_DET

### ISSUE THREAD

**Issue by marcusmsv** [marcusmsv/Nova#368]
Fabio,

Poderia revisar a regra da data de ultima atualização da view Pedido de Venda detalhe.

Pegamos um caso onde na pedido cabeçalho a data de ultima atualização é recente e na detalhe, a data é de 9 meses atras.

O numero da entrega é: 7010046601

Obrigado.

**Comment by fabioInfor** [comment]
Marcus,

Estava usando histórico da linha, mas alterei para usar a maior data entre a capa e a linha da ordem de venda já que extrai dados das duas tabelas. Favor validar

**Comment by marcusmsv** [comment]
Resolvido
