### ISSUE TITLE
VW_DOM_FILIAL_LN

### ISSUE THREAD

**Issue by marcusmsv** [marcusmsv/Nova#369]
Fabio,

Poderia verificar o motivo da view não rodar em produção CIA 301?

Obrigado.

**Comment by fabioInfor** [comment]
Marcus,

Tinha uma conversão para inteiro no campo CD_FILIAL, porem existe um registro com código em branco que usado para conciliação. Alterei a query para não mostrar este registro com código em branco.

**Comment by marcusmsv** [comment]
Resolvido
