### ISSUE TITLE
baandb.ttttxt010201

### ISSUE THREAD

**Issue by marcusmsv** [marcusmsv/Nova#370]
Fabio,

Poderia verificar com o Vergilio de habilitar o campo data do registro na tabela baandb.ttttxt010201

Obrigado.

**Comment by fabioInfor** [comment]
Marcus,

É possível criar o campo, mas para o Vergilio fazer isto é necessário que seja criado um SDP. Voce pode criar um SDP solicitando por favor?

Descreva que voce precisa que seja ativada a data de atualização (rcd_utc) na tabela tttxt010.
