### ISSUE TITLE
Loja Retira na view de cabeçalho do pedido venda

### ISSUE THREAD

**Issue by filipecomparini** [marcusmsv/Nova#371]
Fabio, boa tarde.

Poderia incluir o campo que informa qual a loja que será retirado o produto na view de cabeçalho do pedido.

Qualquer dúvida estou a disposição.

Abs,
Filipe

**Comment by fabioInfor** [comment]
Filipe,

Voce sabe se existe esta informação no LN,procurei nas tabelas de integração de pedido e não encontrei.

**Comment by filipecomparini** [comment]
Fabio, bom dia.

Então vou retirar essa informação da loja.

Obrigado,
Filipe
