### ISSUE TITLE
NFR_CAB (VL_MERCADORIA)

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#373]
Fabio,

A referência Fiscal "R20003812" está apresentando dados na extração da NFR_DET, porém na NFR_CAB o valor da mercadoria está zerado.

Analisando as informações pelas telas do LN, encontramos o seguinte (destacado em vermelho):

![image](https://cloud.githubusercontent.com/assets/7606062/7115545/f8b598cc-e1bf-11e4-9ffc-28627d5b8884.png)

Você poderia verificar esse problema para nós?

Rosana

**Comment by fabioInfor** [comment]
Rosana,

Isto foi um teste feito pelo Fabio Camargo. Isto não deverá acontecer em produção.

**Comment by rosanaprignolato** [comment]
Ok Fabio, o Marcus já fez uma restrição nesta referência Fiscal para a extração dos dados.
