### ISSUE TITLE
VW_TRP_TRANSPORTE (DT_SAIDA_ENTREGA)

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#375]
Fabio, 

Nesta view, o campo DT_SAIDA_ENTREGA possui registros nulos e analisando a extração dos dados identifiquei que a leitura deste campo está sendo realizada somente para as etiquetas que possuem a ocorrência ROT [em rota].  Acontece que algumas etiquetas no LN (Ocorrência de Entregas) não tem a ocorrência ROT. Elas estão somente com as ocorrências ENT (Entregue ao Cliente) e ETR (Entregue a Transportadora). Isso está correto? Segundo o Ricardo, todas deveriam ter o status ROT também.....

A etiqueta "0000002573" encontra-se nesta situação. Este campo de data não pode ter registros nulos em nossa base e caso a rotina esteja certa, precisaremos fazer um tratamento neste campo.

Obrigada
Rosana

**Comment by fabioInfor** [comment]
Rosana,

Conversei com o consultor e ele disse que esta ocorrência "ROT" é a transportadora que informa, e em alguns casos não está sendo informado mesmo. Ele sugeriu alterar para a data da ocorrência "ETR", que é a data que a entrega foi retirada do armazém pela transportadora, esta data sempre deverá existir. Podemos fazer desta forma?

**Comment by rosanaprignolato** [comment]
Ok Fábio, conversei com o Ricardo e ele concordou com a alteração. Você poderia providenciar a alteração da view?

**Comment by fabioInfor** [comment]
Rosana,

Fiz a alteração para considerar o ponto ETR

**Comment by rosanaprignolato** [comment]
Ok, corrigido!
