### ISSUE TITLE
VW_WMS_VOLUMETRIA (Tipo de Bloqueio)

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#376]
Fábio,

Conforme conversamos com o Ricardo, será necessário incluir nesta view o Tipo de Bloqueio para podermos relacionar com a tabela que foi extraída do Front.

**Comment by fabioInfor** [comment]
Rosana,

Inclui o código de bloqueio e a filial para fazer o relacionamento. Tive que usar alguns DBLinks pois o numero da filial só temos no LN.

**Comment by rosanaprignolato** [comment]
Ok Fábio, já fiz a alteração necessária em nossas rotinas. O Riccardo vai conferir e encontrando problemas reabriremos o chamado.
