### ISSUE TITLE
VW_DES_RAZAO_GD - Extração Dados

### ISSUE THREAD

**Issue by marcusmsv** [marcusmsv/Nova#377]
Fabio,

Poderia verificar o motivo do processo de carga dos dados da tabela não conseguir carregar mais que 146.000 registros.

Estou filtrando o ano de 2015 e o mês de 01.

Foram feitas 2 tentativas de carga, com tempo de 10 horas e o segundo de 3 horas e o processo deixa de carregar os dados ao atingir 146.000 registros

Poderia verificar se há algum tipo de bloqueio no LN para as tabelas que são utilizadas na view?

Obrigado.

**Comment by fabioInfor** [comment]
Marcus,

Conforme conversamos alterei a query para considerar a filial da maneira que está cadastrada na contabilidade, desta forma não é necessário fazer um join com a própria tabala de histórico de transação e fica muito mais rápido.

**Comment by marcusmsv** [comment]
Fabio,

Poderia validar com os consultores da Infor, se o campo Filial é obrigatório no LN.

Executei a query modificada, e não identifiquei nenhum caso de filial vazia, que justificaria a recursividade implementada.

Conversei com a Luciana do Planejamento Financeiro, e segundo ela, não há possibilidade de a filial ser carregada vazia.

Poderia verificar?

Obrigado.

**Comment by fabioInfor** [comment]
Marcus,

A obrigatoriedade é definida na configuração da conta contabil conforme mostrado na imagem abaixo.

Veja abaixo exemplo com a filial vazia, repare que isto acontece na linha do histórico do documento e a query reflete o que está no LN.

![image](https://cloud.githubusercontent.com/assets/7606647/7203679/a86ece16-e4f2-11e4-8dd7-b0f56bc40fde.png)


Configuração da conta contabil com valor de filial em branco:
![image](https://cloud.githubusercontent.com/assets/7606647/7203644/719e320a-e4f2-11e4-972c-f26132172b9a.png)

Tela do LN com a transação mostrada na query:
![image](https://cloud.githubusercontent.com/assets/7606647/7203669/8dbdc266-e4f2-11e4-8806-85d7a5612b6b.png)

**Comment by marcusmsv** [comment]
Resolvido
