### ISSUE TITLE
VW_PEC_CAB - Alteração Natureza Operação

### ISSUE THREAD

**Issue by marcusmsv** [marcusmsv/Nova#379]
Fabio,

Conforme verificamos, nos casos onde o pedido não tenha sido recebido, o CFOP que esta sendo carregado esta no nível de linha, gerando duplicidade, uma vez que os itens do pedido de compra pode ter mais de um CFOP.

Poderia alterar a natureza para limitar uma linha quando houver duplicidade, e no BI, assumimos que esse campo poderá sofrer alterações, a na carga vamos incluir uma atualização para este atributo.

Obrigado.

**Comment by fabioInfor** [comment]
Marcus,

Query corrigida, já existia uma regra para extrair o CFO da linha de maior valor porem não estava correto.

**Comment by marcusmsv** [comment]
Resolvido.
