### ISSUE TITLE
Conferência Migração - Estoque LN

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#392]
Marcus,

Foram elaboradas algumas consultas simples para auxiliar na consulta dos dados que geraram esses resultados. Essas consultas encontram-se no servidor Criciuma em: N:\Migracao\Querys_Conferencia\ Estoque_LN.sql

Abaixo seguem as considerações sobre o Estoque LN:

Processo para gerar a tabela " mis_dw.dbo.ods_estoque_sige"
 1 - Qtd registros na tabela mis_dw.dbo.ods_estoque_sige: 16.617 registros
 2 - Qtd registros na tabela mis_dw.dbo.stg_estoque_sige: 16.620 registros
 3 - Qtd registros existentes em ambas tabelas mis_dw.dbo.ods_estoque_sige e mis_dw.dbo.stg_estoque_sige: 16.555 registros

A tarefa "(DFT) ods_estoque_sige" do container "(SC) Fato" do dtsx "ods_estoque.dtsx" está desabilitada

**Comment by marcusmsv** [comment]
Rosana, 

Conforme alinhado com Patrick, este processo ja esta em produção, sendo assim seguimos a mesma ação do processo de adquirente.
