### ISSUE TITLE
Conferência Migração - Lista de Casamento

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#398]
Filipe,

Foram elaboradas algumas consultas simples para auxiliar na consulta dos dados que geraram esses resultados. Essas consultas encontram-se no servidor Criciuma em: N:\Migracao\Querys_Conferencia\ Lista_Casamento.sql

Abaixo seguem as considerações sobre a Lista de Casamento:

Processo para gerar a tabela "mis_dw.dbo.ods_lista_casamento_sige"
 1 - Qtd registros na tabela mis_dw.dbo.ods_lista_casamento_sige: 349 registros
 2 - Qtd registros na tabela mis_dw.dbo.stg_sige_lista_casamento: 118 registros
 3 - Qtd registros existentes em ambas tabelas mis_dw.dbo.ods_lista_casamento_sige e mis_dw.dbo.stg_sige_lista_casamento: 118 registros

Processo para gerar a tabela “mis_dw_dbo.ods_lista_casamento_loja"
 1 -Qtd registros na tabela mis_dw.dbo.ods_lista_casamento_loja: 1.853.231 registros
 2 - A leitura das tabelas de origem não retornam dados: mis_dw.dbo.stg_lista_de_compra, mis_dw.dbo.stg_lista_casamento, mis_dw.dbo.stg_lista_de_compra_item

Processo para gerar a tabela “mis_dw.dbo.ods_lista_casamento_produtos_comprados_com_vale"
 1 - Qtd registros na tabela mis_dw.dbo.ods_lista_casamento_produtos_comprados_com_vale: 65 registros
 2 - a leitura das tabelas de origem não retornam dados: mis_dw.dbo.ods_approved

Processo para gerar a tabela “mis_dw.dbo.ods_lista_casamento_loja_lista_invalida"
 1 - Qtd registros na tabela mis_dw.dbo.ods_lista_casamento_loja_lista_invalida: 4.473 registros
 2 - a leitura das tabelas de origem não retornam dados: mis_dw.dbo.stg_lista_casamento, mis_dw.dbo.stg_lista_de_compra

Processo para gerar a tabela “mis_ods.mkt.ods_rpt_lista_casamento"
 1 - Qtd registros na tabela mis_ods.mkt.ods_rpt_lista_casamento: 82.151 registros
 2 - Qtd registros na tabela mis_staging.mkt.stg_rpt_lista_casamento: 82.130 registros
3 - Qtd registros existentes em ambas tabelas mis_ods.mkt.ods_rpt_lista_casamento e mis_staging.mkt.stg_rpt_lista_casamento: 82.104 registros

No dtsx "ssis_controlador_lista_casamento.dtsx", as tarefas "(EPT) Lista CB", "(EPT) Lista PF", "(EPT) Auditoria Item" e "(EPT) OLAP Lista" estão desabilitadas

No dtsx "staging lista casamento loja.dtsx", as tarefas "(SQL) Limpa tabelas staging", "(SQL)

**Comment by filipecomparini** [comment]
Rosana,

Verifiquei o processo como um todo e ajustei alguns problemas. Um deles foi o ajuste do meio de pagamento que vinha do approved e fiz um tratamento na descrição do canal de vendas.

Abs,
Filipe
