### ISSUE TITLE
Conferência Migração - Purchase Full

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#404]
Marcus,

Foram elaboradas algumas consultas simples para auxiliar na consulta dos dados que geraram esses resultados. Essas consultas encontram-se no servidor Criciuma em: N:\Migracao\Querys_Conferencia\ Purchase_Full.sql

Abaixo seguem as considerações sobre Purchase Full:

Processo para gerar a tabela “mis_dw.dbo.ods_purchase_full “
 1 - Qtd registros na tabela mis_dw.dbo.ods_purchase_full: 13.803 registros
 2 - Qtd registros na tabela mis_dw.dbo.stg_sige_purchase_full: 238 registros
 3 - Qtd registros existentes em ambas tabelas mis_dw.dbo.ods_purchase_full e mis_dw.dbo.stg_sige_purchase_full: 195 registros

**Comment by marcusmsv** [comment]
Rosana, 

Conforme alinhado com Patrick, este processo ja esta em produção, sendo assim seguimos a mesma ação do processo de adquirente.
