### ISSUE TITLE
Conferência Migração - Purchase Open

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#405]
Marcus,

Foram elaboradas algumas consultas simples para auxiliar na consulta dos dados que geraram esses resultados. Essas consultas encontram-se no servidor Criciuma em: N:\Migracao\Querys_Conferencia\ Purchase_Open.sql

Abaixo seguem as considerações sobre Purchase Open:

Processo para gerar a tabela “mis_dw.dbo.ods_sige_cmv_hist “
 1 - Qtd registros na tabela mis_dw.dbo.ods_sige_cmv_hist: 139.523 registros
 2 - Qtd registros na tabela mis_dw.dbo.stg_sige_cmv_hist: 139.499 registros
 3 - Qtd registros existentes em ambas tabelas mis_dw.dbo.ods_sige_cmv_hist e mis_dw.dbo.stg_sige_cmv_hist: 139.523 registros

**Comment by marcusmsv** [comment]
Rosana, 

Conforme alinhado com Patrick, este processo ja esta em produção, sendo assim seguimos a mesma ação do processo de adquirente.
