### ISSUE TITLE
VW_WMS_Pedido_Det - Correção CD_LOTE

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#418]
Fábio,

Conforme conversamos, fazer a alteração da leitura do Lote para esta view.

**Comment by fabioInfor** [comment]
Rosana,

Alteração concluída

**Comment by rosanaprignolato** [comment]
Ok Fábio!

Agora precisamos da correção na quantidade cancelada. Precisamos que seja considerado neste campo apenas o valor da Quantidade Ajustada quando o mesmo for menor do que zero. A quantidade cancelada deve ser apresentada em valor absoluto.

**Comment by fabioInfor** [comment]
Rosana,

Alterei a quantidade cancelada

**Comment by rosanaprignolato** [comment]
Ok Fábio, já recarreguei os dados. Coloquei no mapeamento da conferência que essa coluna não é apresentada em tela para conferência.
