### ISSUE TITLE
VW_WMS_VOLUMETRIA - Correção da leitura de valores

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#423]
Fábio,

Segue a view que eu alterei para corrigir a leitura dos valores. Fiz apenas para o armazém 1. Por favor, veja se está correto e replique para os demais:

select 
  ll.sku CD_SKU,
  ll.sku CD_ITEM,
  CASE WHEN TO_CHAR(ll.holdreason)=' ' THEN 'WN' ELSE TO_CHAR(ll.holdreason) END CD_BLOQUEIO,
  pz.PUTAWAYZONE CD_CLASSE_LOCAL,
  ll.loc CD_LOCAL,
  subStr(cl.DESCRIPTION,3,6) CD_ARMAZEM,
  sum(llid.qty) QT_PC,
  sum(llid.netwgt) QT_PESO,
  sum(sku.STDCUBE*llid.qty) QT_M3,
  llid.WHSEID CD_ARMAZEM_WMS
from 
WMWHSE1.lotxloc ll,

WMWHSE1.lotxlocxid llid
 left join (select whseid, sku, sum(STDCUBE) stdcube from WMWHSE1.sku group by whseid, sku) sku
 on sku.whseid = llid.WHSEID and sku.sku = llid.SKU,

WMWHSE1.loc
 LEFT JOIN WMWHSE1.PUTAWAYZONE pz on pz.PUTAWAYZONE=loc.PUTAWAYZONE,

ENTERPRISE.CODELKUP cl

where ll.sku = llid.sku and ll.loc = llid.loc and ll.lot = llid.lot
AND ll.loc=loc.loc
AND cl.LISTNAME = 'SCHEMA'
AND UPPER(cl.UDF1)=llid.WHSEID
--and ll.sku = '112483'

group by
ll.sku,
ll.holdreason,
ll.loc,
pz.PUTAWAYZONE, 
cl.DESCRIPTION,
llid.WHSEID,
sku.STDCUBE

Obrigada
Rosana

**Comment by fabioInfor** [comment]
Rosana,

A query está correta, quer que eu atualize no Github?

**Comment by rosanaprignolato** [comment]
Fábio,

Por favor, atualize no GitHub para que eu possa efetivar as mudanças realizadas.

Obrigada

**Comment by fabioInfor** [comment]
Rosana,

Alterei a query.

**Comment by rosanaprignolato** [comment]
Ok Fábio, já atualizei a query nas rotinas
