### ISSUE TITLE
VW_WMS_Pedido_Cab

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#424]
Fábio,

Nesta view, após a conferência dos dados com as telas do WMS, encontrei as dúvidas que relaciono abaixo:

1) DT_MINIMA_EXPEDICAO e DT_LIMITE_ORIGINAL : estão considerando o mesmo campo para a leitura (orders.DELIVERYDATE)

2) CD_ROTA e CD_CONTRATO_TRANSPORTADORA : estão considerando o mesmo campo para a leitura (ORDERS.ROUTE)

Você poderia verificar se isso está correto?

Obrigada
Rosana

**Comment by fabioInfor** [comment]
Rosana,

Não sei o que significa estas datas, na época que desenvolvemos a query ficou como ponto de dúvida. Acredito que estas datas precisem ser extraídas do LN, mas para fazer isto precisamos do significado de cada uma.

No WMS temos as datas abaixo, algumas já estão no relatório, veja se alguma atende a necessidade.

SCHEDULEDSHIPDATE - Data programada de expedição, que recebe o valor da data limite de expedição que vem do front

SCHEDULEDDELVDATE - Data programada de entrega, que é a data de entrega combinada com o cliente

DELIVERYDATE - Data de entrega, antes de ser entregue tem o mesmo valor que SCHEDULEDDELVDATE depois recebe a data real de entrega

ORDERDATE - Data que a ordem foi criada

**Comment by rosanaprignolato** [comment]
Ok Fábio, vou encaminhar para o Riccardo analisar e nos responder. Com relação ao CD_ROTA e CD_CONTRATO_TRANSPORTADORA, está correto considerar o mesmo campo para a leitura, no caso (ORDERS.ROUTE)?

**Comment by rosanaprignolato** [comment]
Fábio,

Conversei com o Riccardo sobre as datas e ele solicitou que fizessemos da seguinte maneira:

1) DT_MINIMA_EXPEDICAO: manter o campo que está sendo lido (orders.DELIVERYDATE)

2) DT_LIMITE_ORIGINAL: pegar a informação do campo (orders.SCHEDULEDSHIPDATE)

Com relação ao CD_ROTA e CD_CONTRATO_TRANSPORTADORA, está correto considerar o mesmo campo para a leitura, no caso (ORDERS.ROUTE)?

Obrigada
Rosana

**Comment by fabioInfor** [comment]
Rosana,

Alterei o DT_LIMITE_ORIGINAL, o código do contrato não existe no WMS somente no LN.

**Comment by rosanaprignolato** [comment]
Ok Fábio, porém a view não está no GitHub. Você poderia colocá-la?

Obrigada
Rosana

**Comment by rosanaprignolato** [comment]
Ok Fábio. Já fiz a correção da view.
