### ISSUE TITLE
VW_WMS_TRACKING_PEDIDO - DT_INCLUSAO_VL_CARGA

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#425]
Fábio,

Não consegui identificar de onde conferir o campo utilizado para a "DT_INCLUSAO_VL_CARGA". A view está utilizando o campo "WMWHSE1.CAGEIDDETAIL.adddate". 

Você poderia me orientar em como obter essa informação pela tela do WMS?

Obrigada
Rosana

**Comment by fabioInfor** [comment]
Rosana,

Os dados da tabela CAGEIDDETAIL são mostradas na tela abaixo, porem o campo AADDATE não é mostrado. Este campo representa a data que o volume foi incluído na gaiola mas a unica forma de visualizar é consultando na tabela.

![image](https://cloud.githubusercontent.com/assets/7606647/7482659/7092c752-f34f-11e4-8525-9e3116eb7999.png)

**Comment by rosanaprignolato** [comment]
Ok Fábio, vou colocar na documentação que esse campo só é visto através da tabela.

Mais um detalhe nesta view que eu reparei somente agora. O campo DT_ULT_ATUALIZACAO está com a seguinte leitura:

(SELECT CAST((FROM_TZ(TO_TIMESTAMP(TO_CHAR(MIN(OSH.ADDDATE), 'DD-MON-YYYY HH24:MI:SS'), 'DD-MON-YYYY HH24:MI:SS'), 'GMT') 
          AT time zone 'America/Sao_Paulo') AS DATE) FROM WMWHSE1.ORDERSTATUSHISTORY OSH 
          WHERE OSH.ORDERKEY=OD.ORDERKEY) DT_ULT_ATUALIZACAO

Por se tratar da data da última atualização, está correto usar a função MIN para pegar a data? Não teríamos que trabalhar com a data mais recente? Outra dúvida é se esse campo eu consigo pegar na tela para conferir.

Por favor, veja se minha consideração procede. Se sim, poderia corrigir e colocar a view no GitHub?

Obrigada
Rosana

**Comment by fabioInfor** [comment]
Rosana,

Tem razão, deveria usar a maior data. Já alterei a query.

**Comment by rosanaprignolato** [comment]
Ok Fábio, já alterei as rotinas de carga.
