### ISSUE TITLE
NIKE - NK_Clientes_Varejo

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#426]
Fábio,

Abaixo seguem algumas dúvidas geradas com a conferência das informações desta view:

1) Campo "CADASTRAMENTO" : Atualmente a view está trabalhando com o campo "stdt" (Data inicial) da tabela ttccom100. O correto não seria pegar a data de criação (crdt)? Se o correto for o campo "stdt", como eu valido a data inicial pela tela?

2) Campo "TELEFONE": O DDD já está separado em uma coluna. É correto mantê-lo junto com o número do telefone, como encontra-se atualmente no cadastro do LN?

3) Campo "DDD_CELULAR": A view está buscando as duas primeiras posições do campo "telx" ( Telefone 2) da tabela tccom130, porém não achei essa informação em tela.

4) Campo "CELULAR": A view está buscando o campo "telx" ( Telefone 2) da tabela tccom130, porém não achei essa informação em tela

Obrigada 
Rosana

**Comment by fabioInfor** [comment]
Rosana,

Fiz as correções e carreguei a query no Github, abaixo respostas:

1 - Alterado para "data de criação"

2 - No LN temos somente um campo para para DDD e telefone, criamos um SUBSTR para considerar sempre os dois primeiros numeros como DDD. Avise se preferir carregar tudo em um campo só.

3 - Alterei pois o correto é buscar na tabela de pedidos integrados. Não temos um campo específico para numero do celular, somente os campos telefone, telefone 2 e telefone 3 na tabela de integração de pedidos e estamos considerando o telefone 2 como celular.

4 - Alteramos para buscar na tabela de pedidos integrados (znsls400) voce pode verificar na sessão znslsc500m000

**Comment by rosanaprignolato** [comment]
Ok Fábio! Já efetuei as correções. Com relação aos campos DDD e Telefone, vamos deixa-los separados mesmo. Reparei que nesta nova view, no telefone você pegou os dados a partir da terceira posição para considerar somente o numero do telefone.
