### ISSUE TITLE
NIKE - NK_Loja_NF

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#428]
Fábio,

Encontrei as seguintes inconsistências nesta view:

1) A view está trazendo duas vezes a DATA_SAIDA

2) VOLUMES: nas entradas está trazendo a mesma informação que "QTDE_TOTAL" e nas saídas está lendo os dados do campo t$etiq$c da tabela znfmd610, porém a única sessão que trabalha com essa tabela deve ser acessada através de outra. Encontrei no menu da NovaPontocom a sessão "znfmdc181m000" (Packing List - Consulta por Transportadora/Gaiola], porém não tenho permissão para acessá-la.

3) OBS: Teremos que ver com o Patrick como trataremos a leitura dos dados da tabela TTTXT010, pois a mesma é bem grande

Obrigada
Rosana

**Comment by hkasai** [comment]
Rosana, boa tarde,

1 ) A definição possui dois campos de DATA_SAIDA, linha 12 e 59. Na primeira ocorrência estamos passando a data de saída da NF. A segunda ocorrência foi corrigida para notas de Saída, onde estamos passando a ocorrência "ETR" do Tracking de Pedidos. As notas de Entrada continuam com os mesmos campos. Alterei o nome dos campos para não haver duplicidade. A query foi atualizada no Github.

2 ) O usuário para consulta da sessão deve ser cadastrada na sessão "Perfis do Usuário", fmfmd1120m000. Quanto às notas de Entrada, na definição original, a quantidade do campo "Volumes" está 0. A query foi corrigida e atualizada no Github.

3 )  Quando à tabela de textos, conversamos com o Patrick.

Grato, Humberto.

**Comment by rosanaprignolato** [comment]
Humberto,

Ainda restaram algumas dúvidas:

1) Na leitura das datas de saídas, no movimento de saída, vi que você alterou a tabela de origem dos dados, porém, no movimento de entrada, ele continua lendo o mesmo campo para ambas as datas (Saída NF e Saída ETR). É isso mesmo?

2) Eu acessei a sessão de "Perfis de Usuário", mas o meu usuário eu não encontrei nessa sessão. É possível você me ajudar com esse item?

Obrigada
Rosana

**Comment by rosanaprignolato** [comment]
Humberto,

Conforme conversamos, alterar o VOLUME para ler das Ordens de Frete.

**Comment by hkasai** [comment]
Rosana,

A query foi alterada para contar as etiquetas pela nota fiscal.

Grato, Humberto.

**Comment by rosanaprignolato** [comment]
Humberto,

Já fiz a atualização da view e mapeei a conferência da mesma com o LN, porém, precisamos acertar um conceito sobre a leitura dos dados para a informação QTDE_TOTAL. Segundo o Rodrigo, é o seguinte:

QTDE_TOTAL: é a soma das quantidades faturadas (Saída) / Vendidas (Entrada) dos itens, exceto Garantia, Frete, despesas etc. Ex: item A - foram faturadas/vendidas 15 peças ; item B - foram faturadas/vendidas 20 peças ==> QTDE_TOTAL = 35

QTDE_CANCELADA: o mesmo conceito da QTDE_TOTAL, porém apenas para os cancelamentos

Você poderia providenciar a correção desta informação?

Obrigada
Rosana

**Comment by hkasai** [comment]
Rosana,

Fiz a correção do campo para não considerar os itens de frete, despesas e juros.

Grato, Humberto.

**Comment by rosanaprignolato** [comment]
Humberto,

Ainda temos problemas com o campo QTDE_TOTAL. A view continua somando todos os itens, inclusive Frete. Utilizei como conferência a Ref Fiscal F20000746.

Outra dúvida é com o campo PROTOCOLO_CANCELAMENTO_NFE. Essa mesma referência fiscal não está com o status transmissão cancelada, no entanto, esse campo está sendo alimentado com a mesma informação existente no campo PROTOCOLO_AUTORIZACAO_NFE. O protocolo de cancelamento não teria que ser informado somente em caso de cancelamento?

A observação eu valido como pelas telas do LN?

Campo ENTREGA_CIDADE e ENTREGA_BAIRRO. Ainda nesta mesma referência fiscal F20000746, no endereço de entrega eu tenho a cidade e o bairro, porém a view não está trazendo nada.

![image](https://cloud.githubusercontent.com/assets/7606062/7659135/3399f428-fb16-11e4-9ff9-e6a296d79de1.png)

Você poderia analisar esses problemas?

Obrigada
Rosana

**Comment by hkasai** [comment]
A quantidade total, cidade e bairro foram corrigidos na query. 

O campo "Observação Nota Fiscal" pode ser verificado na tela da NF, como segue:

![image](https://cloud.githubusercontent.com/assets/8986936/7661592/4bb40666-fb2a-11e4-8972-3f83e7ca88ad.png)

**Comment by rosanaprignolato** [comment]
Ok Humberto, 

A query foi atualizada e validada. Obrigada!
