### ISSUE TITLE
NIKE - NK_Loja_NK_Item

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#429]
Fábio,

Mapeando as telas para conferência dos dados desta view, encontrei as seguintes inconsistências:

1) OBS_ITEM: Está buscando os dados da tabela imensa ttttxt010 e precisaremos ver com o Patrick como faremos esse tratamento. Independente disso, eu não consegui identificar como conferir essa informação nas telas do LN. 

2) VALOR_DESCONTOS: Está lendo o mesmo campo utilizado para DESCONTO_ITEM. Isso está correto?

3) DESCRICAO_ITEM: A view original estava com esse campo em branco. Conversando com o Fábio, combinamos de pegar a descrição da tabela de Itens - Geral, entretanto, como a leitura deste dado pode ser feita tanto da tabela ttcibd001 quanto da tabela ttcibd004 eu não me senti segura de corrigir a view. Temporariamente coloquei para buscar a descrição das tabelas de movimento (Rec Fiscal ou Nota Fiscal), mas precisamos que seja corrigido para trazer do local correto.

Obrigada
Rosana

**Comment by hkasai** [comment]
Rosana, boa tarde,

Seguem as respostas:

1 ) Executei a query em Homologação e Produção, e aparentemente está bem rápida. A rotina utiliza a chave primária da tabela, a busca deveria ser rápida. O texto fiscal do item encontra-se na aba "Dados Itens Nova".

2 ) O campo VALOR_DESCONTOS foi zerado, segundo definição original. A query foi atualizada no Github.

3 ) A descrição do item tem que vir da nota fiscal, pois a descrição do item pode ser alterada. Os campos estão corretos.

Qualquer outra dúvida, estamos à disposição.

Grato, Humberto.

**Comment by rosanaprignolato** [comment]
Ok Humberto. Já efetivei as correções.

Obrigada
