### ISSUE TITLE
NIKE - NK_Loja_Venda

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#430]
Fábio,

1) QTDE_ITEM : está somando todas as quantidades existente para todos os itens existentes, inclusive dados de Garantia, Frete.... isso está correto?

2) QTDE_TROCA_TOTAL e QTDE_ITEM : Para a leitura dos dados de coleta, esses campos estão trazendo os dados do mesmo lugar (TDREC941.T$QNTY$L). Isso é correto?

Obrigada
Rosana

**Comment by fabioInfor** [comment]
Rosana,

1) Podemos usar o campo ZNSLS401.T$QTVE$C para obter a soma da quantidade de produtos, porem o campo QTDE_TOTAL já mostra esta informação. Será que o campo QTDE_ITEM não deveria ser a contagem de itens distintos?

2) O campo TDREC941.T$QNTY$L é a quantidade recebida da devolução, este só é usado nas linhas de coleta e mostra a quantidade total que foi recebida. Acho que pode ser o mesmo problema que o ponto 1, precismos diferenciar a diferença destas quantidades para mostrar as informações corretas.

At,
Fabio Ferreira.

**Comment by rosanaprignolato** [comment]
Fábio,

Conversei com o Rodrigo e ele me explicou o seguinte sobre as quantidades:

QTDE_TOTAL : é a soma das quantidades faturadas (Saída) / Vendidas (Entrada) dos itens, exceto Garantia, Frete, despesas etc. Ex: item A - foram faturadas/vendidas 15 peças ; item B - foram faturadas/vendidas 20 peças ==> QTDE_TOTAL = 35

QTDE_ITEM : é a contagem distinta dos itens faturados (Saída) / vendidas (entrada). Ex: Item A - foram faturados/vendidos 15 peças ;  item B - foram faturadas/vendidas 20 peças ; item B - foi faturado/vendido novamente mais 2 peças ==> QTDE_ITEM = 2

QTDE_TROCA_TOTAL: é o mesmo conceito do QTDE_TOTAL, ou seja, a soma dos itens trocados

Você poderia providenciar a correção da view?

Obrigada
Rosana

**Comment by fabioInfor** [comment]
Rosana,

Fiz as alterções, favor validar.

**Comment by rosanaprignolato** [comment]
Fábio,

Agora eu importei os dados para uma tabela SQL e encontrei problemas com a formatação dos campos "CD_CGC_CPF" e "CD_CPF_CGC_ECF".

Peguei como exemplo de conferência CD_TICKET ="0000002131" no movimento de saida

Existe uma observação nesta view dizendo para "VERIFICAR FORMATAÇÃO".

Você poderia verificar?

Obrigada
Rosana

**Comment by fabioInfor** [comment]
Rosana,

Na especificação pede para mostrar o CGC / CPF sem separadores, verifiquei que o campo que estamos estraindo esta informação (tabela de integraçãao) já está como somente numero (veja tela abaixo). Então acredito que não há necessidade de tratamento desse campo.

![image](https://cloud.githubusercontent.com/assets/7606647/7734182/a586ac5a-ff0a-11e4-83e6-dca3057c441a.png)

**Comment by rosanaprignolato** [comment]
Fábio,

Já corrigi a apresentação do CNPJ. No minha tabela ele estava entendendo que era numérico e colocava casas decimais. Coloquei um TO_CHAR na leitura dos dados e deu certo.

Na leitura das coletas, a coluna "QT_TROCA_TOTAL" e "QT_ITEM" estão considerando as informações de "Não Produto". Isso está correto? Estou conferindo os dados do Pedido "000002118", Sequencial "2" e nele temos a seguinte situação:

![image](https://cloud.githubusercontent.com/assets/7606062/7748860/de290ac8-ff9e-11e4-88c8-c6c5cb225685.png)

Diante disso, as informações trazidas pela view indica a "QT_TROCA_TOTAL" = 2, assim como a contagem distinta dos item "QT_ITEM" = 2.

Você poderia verificar se isso está correto?

Obrigada
Rosana

**Comment by fabioInfor** [comment]
Rosana,

Nesse caso está será devolvido o produto e a garantia estendida, acho que está correto aparecer a quantidade do jeito que está mas confirme com o Rodrigo.

Acho que na Nike vamos ter itens "não produto" referente as customizações do produtos, a query for desconsiderar a garantia estendida na soma precisamos verificar se deve fazer o mesmo com as customizações.

**Comment by rosanaprignolato** [comment]
Fábio,

Conversei com o Rodrigo e o Patrick e ambos disseram que só devemos considerar produtos. Com relação às customizações, será necessário rever também.

Você poderia verificar?

Obrigada
Rosana

**Comment by fabioInfor** [comment]
Rosana,

Alterei a query para não considerar os "não produtos" nos campos QT_ITEM, QT_TOTAL, QT_TROCA_TOTAL.

**Comment by rosanaprignolato** [comment]
Ok Fábio! View atualizada e dados corrigidos.
