### ISSUE TITLE
NIKE - NK_Loja_Venda_Pagto_Parcelas

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#432]
Fabio,

1) VALOR: Na leitura das Vendas, o valor está considerando a soma dos dados do item e também da Garantia Estendida. Isso está correto?

2) DATA_HORA_TEF: Na leitura da coleta e da instância, está sendo considerada a mesma data que DATA_VENDA. Isso é correto?

Obrigada
Rosana

**Comment by fabioInfor** [comment]
Rosana,

1) O campo valor deve representar tudo o que foi pago, porem como estava usando o valor da nota fiscal poderia acontecer de ter mais de um meio de pagamento e duplicar o valor. Alterei para usar o valor pago do meio de pagamento que é carregado na tabela de integração.

2) Estava errado para coleta e instancia, já corrigido.

**Comment by rosanaprignolato** [comment]
Ok Fábio, view atualizada e dados corrigidos.
