### ISSUE TITLE
NIKE - NK_Loja_Venda_Produto

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#433]
Fábio,

1) PRODUTO : Nas Vendas está sendo considerado inclusive as linhas de Frete. Isso está correto?

2) ALIQUOTA : Nas vendas esse campo está trazendo a Alíquota de ICMS, porém o Valor é referente ao IPI. Isso está certo?

3) CUSTO : Tanto em vendas como em instância, eu não consegui chegar no valor de custo apresentado pela view. Você poderia me orientar? Em vendas eu estava usando os itens 299027 e 68176, ambos do armazém A00200. Já em instância, os itens 299027 e 209457, pelo que eu identifiquei, o armazém está com zero. Veja a imagem:

![image](https://cloud.githubusercontent.com/assets/7606062/7658022/06d3465a-fb0d-11e4-952e-d721d0a8f752.png)

Obrigada
Rosana

**Comment by fabioInfor** [comment]
Rosana,

1) Criei uma condição para não mostrar os itens frete / juros...

2) A coluna "Alíquota" está correta pois na definição diz que é a alíquota de ICMS, a coluna IPI estava errado pois na definição diz que é a alíquota e estava mostrado o valor (corrigido)

3) O custo eu alterei para que seja extraído de outra tabela pois onde estava sendo extraído não exites os custo para os itens que não tem estoque (games, download, ...). Agora voce pode verificar na tela abaixo. O valor da tela precisa ser dividido pela quantidade, pois é o valor total.

![image](https://cloud.githubusercontent.com/assets/7606647/7662373/0b17051a-fb32-11e4-9b9f-1a4148c36438.png)

**Comment by rosanaprignolato** [comment]
Fábio,

Já fiz a atualização da view e os problemas reportados foram corrigidos. 

Obrigada
Rosana
