### ISSUE TITLE
NIKE - NK_Loja_Venda_Troca

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#434]
Fábio,

Conforme conversamos, teremos que mudar a leitura do CUSTO desta view também, seguindo o mesmo modelo que você utilizou na view "NK_Loja_Venda_Produto".

Você poderia providenciar a correção?

Obrigada
Rosana

**Comment by fabioInfor** [comment]
Rosana, alterei a query.

**Comment by rosanaprignolato** [comment]
Fábio,

Fiz a atualização da view, porém estou com dificuldade para conferir alguns dados:

O Ticket "210400AA" possui a Ref Fiscal "R00000320" e o Pedido de Venda "V20000546". o item é "68176". Indo para a sessão "tdsls4115m000" (COGS - Estimado da Ordem de Venda) e informando esse pedido de venda, o valor do custo apresentado para esse item é R$ -50,00, porém a view está trazendo um valor positivo.

Você poderia me ajudar a identificar isso?

Obrigada
Rosana

**Comment by fabioInfor** [comment]
Rosana,

Na ordem de venda o valor aparece sempre negativo nessa tela, eu criei um regra para mostrar o valor absoluto para não fazer confusão.

Avise se preferir que mostre negativo.

At,
Fabio Ferreira.

**Comment by rosanaprignolato** [comment]
Ok Fábio, conversei com o Rodrigo e o valor deve vir mesmo absoluto.
