### ISSUE TITLE
NIKE - NK_Loja_NF_Item

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#435]
Fábio,

Esta view está trazendo linhas de Frete, Garantia, outras despesas.... como item. Isso está correto?

Veja o documento 101, série 13 no movimento de Saída.

Obrigada

Rosana

**Comment by hkasai** [comment]
Rosana,

Os itens de frete, despesas e juros foram retirados da query, de acordo com os itens parametrizados na tabela "znsls000".

Grato, Humberto.

**Comment by rosanaprignolato** [comment]
Ok Humberto, a view foi atualizada e a solicitação foi atendida.
