### ISSUE TITLE
BUNZL - VW_BZL_Clientes

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#436]
Fábio,

Estou conferindo os dados extraídos e encontrei o seguinte problema:

CD_INSCR_EST : o cliente com o CD_SEQUENCIAL "000001988" e Complemento Fiscal "325229998-42" possui a Inscrição Estadual como ISENTO na tela do LN, porém a view está apresentando "1010722906". 

Você poderia verificar?

Obrigada
Rosana

**Comment by fabioInfor** [comment]
Rosana,

Eu acho que é um problema de cadastro, pois tem um complemento fiscal cadastrado com código em branco na CIA 201. Fiz uma alteração na query para desconsiderar o complemento fical com código em branco.

At,
Fabio Ferreira.

**Comment by rosanaprignolato** [comment]
Ok Fábio, corrigido!
