### ISSUE TITLE
VW_DEV_DEVOLUCAO - Registros Duplicados

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#439]
Humberto,

Essa view está retornando registros duplicados. Usei como base a NR_REFERENCIA_FISCAL_FATURA = 'F70000193'

Você poderia analisar?

Obrigada

**Comment by hkasai** [comment]
Rosana,

A entrega (tdsls406) e o recebimento (tdrec947) estava particionada em 5 partes, por isto estava lendo 5 vezes cada tabela, resultando nos 25 registros.
Corrigi a query para ler somente a primeira(o) entrega/recebimento destas tabelas, quando as mesmas estiverem particionadas.

Grato, Humberto.

**Comment by rosanaprignolato** [comment]
Ok Humberto! Executei a view e agora só está retornando um registro.

**Comment by rosanaprignolato** [comment]
Fábio, ao executar a view corrigida pelo Humberto, encontrei problema em 2 registros que estão trazendo dados de conhecimento de frete.

A chave primária da minha tabela é composta pelos campos: CD_CIA, CD_FILIAL, DT_FATURA, CD_ITEM, NR_REFERENCIA_FISCAL_FATURA e NR_REFERENCIA_FISCAL_REMESSA

Os registros com problema são:

![image](https://cloud.githubusercontent.com/assets/7606062/8655007/ad406dbc-2964-11e5-8797-9c02d6d34853.png)

Analisando pela tela do LN encontro o seguinte:

CD_ITEM = '209457', possui a NF "23456" e "83", com a referência Fiscal de Devolução "R00001795" e "R00001793", respectivamente. Porém apenas uma delas (NF 83) é retorno de mercadoria. A NF 23456 é Conhecimento de Frete.

Já para a outra situação, CD_ITEM "2171481", vejo isso no LN:

![image](https://cloud.githubusercontent.com/assets/7606062/8655150/b1c72aaa-2965-11e5-8924-115b0e5a844f.png)

Você poderia verificar o que está errado na view?

Obrigada

**Comment by fabioInfor** [comment]
Rosana,

Fiz uma alteração na query para não relacionar as referências fiscais de conhecimento de transporte. Veja se funcionou para todos os casos.

At,
Fabio Ferreira.

**Comment by rosanaprignolato** [comment]
Fábio,

Executei a nova view e não encontrei problemas. Os casos relatados agora retornaram apenas um registro pra cada.

Obrigada
