### ISSUE TITLE
VW_NK_DEV_DEVOLUCAO - Não retorna registro

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#440]
Humberto,

A view de devolução da NIKE não está retornando registro, porém, pela tela do LN temos um registro de retorno de mercadoria. Conforme conversamos, o código da referência fiscal deste registro está estranho (SG0000001). Abaixo segue a sequência de sessões que foram pesquisadas no LN para encontrar o registro:

Sessão "tdrecl504m50l" (Rec. Fiscal - Sumário)

![image](https://cloud.githubusercontent.com/assets/7606062/8576686/2f7d3984-257a-11e5-9a3f-793a02e74456.png)

Faço o detalhamento desta linha. Na próxima tela apresentada, na aba inferior "linhas", eu detalho novamente. Na aba superior "NOVA" eu pego a informação "Dev.Venda - Referência":

![image](https://cloud.githubusercontent.com/assets/7606062/8576813/095f58ee-257b-11e5-8e0c-81af8782295a.png)

Vou para a sessão "cislil504m00l" (Nota Fiscal) e informo essa referência, porém não a encontro:

![image](https://cloud.githubusercontent.com/assets/7606062/8576892/66aae356-257b-11e5-981a-0099b7738f17.png)

Você poderia analisar o problema?

Obrigada

**Comment by hkasai** [comment]
Rosana,

Analisei a query e encontrei 2 problemas. 

O primeiro problema é referente à Nota Fiscal de Venda, 'SG0000001'. Esta referência é do SIGE e só pode ser encontrada na sessão 'tcmcsc518m000', que utiliza a tabela 'znmcs096'. Quando o pedido vier do SIGE, a tabela deve ser utilizada para encontrar a Nota Fiscal de Venda.

Hoje a query não utiliza esta tabela, utiliza o próprio registro da devolução do pedido (znsls401) para encontrar a nota de venda.

Só não entendi porque a query não tem esta funcionalidade, então peço que envie este comentário para o Fabio validar.

O segundo problema é que a Nota Fiscal de Devolução de Venda não foi gerada. A geração da nota é obrigatória para a impressão do registro.

Qualquer dúvida, pode pedir para o Fabio me ligar no celular.

Grato, Humberto.

**Comment by rosanaprignolato** [comment]
Fábio,

Você poderia analisar esse problema da NIKE?

Obrigada

**Comment by fabioInfor** [comment]
Rosana,

Conversei com a equipe do fiscal e eles disseram que esta devolução foi um teste e está incompleto. Pode desconsiderar este caso pois isto não deve acontecer em produção.

Nos casos de recebimento de devolução sempre deverá ser criada um referencia fiscal de retorno de mercadoria.

**Comment by rosanaprignolato** [comment]
Ok Fábio, obrigada!
