### ISSUE TITLE
NIKE - VW_NK_EST_ESTOQUE

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#442]
Fábio, 

Conforme conversamos, verificar nesta views os valores do item '900000001', pois a mesma está retornando valores que não batem com a tela do LN. Segue o resultado da view:

![image](https://cloud.githubusercontent.com/assets/7606062/8752814/32f4e2a0-2c8d-11e5-95a8-dbed1fabd05f.png)

Pelo LN temos esses dados:

![image](https://cloud.githubusercontent.com/assets/7606062/8752830/5294d890-2c8d-11e5-881b-a591311b528d.png)

**Comment by fabioInfor** [comment]
Rosana,

Tive que fazer uma alteração na query pois na Nike teremos o código de lote como ID da customização e baixas para ordem de produção que não deverão ser consideradas com romaneadas.

A query atualizada já está no Github.

**Comment by rosanaprignolato** [comment]
Ok! View Corrigida e atualizada.
