### ISSUE TITLE
NIKE - Faturamento e Nota Fiscal Cabeçalho

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#443]
Humberto,

Conforme o Marcus te explicou, usamos como parâmetro de conferência a Referência Fiscal "F00000035". No LN temos a seguinte situação para a mesma:

Na tela Principal da Nota Fiscal, essa referência encontra-se com o "Status da Fatura" = Impresso:

![image](https://cloud.githubusercontent.com/assets/7606062/9043478/285c56ea-39ec-11e5-8bde-0124330adc95.png)

Fazendo o detalhamento da mesma, encontramos na NF-e o "Status da NF-e" = Pedido de Cancelamento:

![image](https://cloud.githubusercontent.com/assets/7606062/9043507/5a57f6c2-39ec-11e5-98ab-ae9635ca3b96.png)

Obrigada
Rosana

**Comment by hkasai** [comment]
Rosana,

Os status estão diferentes, pois o GNFe da Homologação estava fora ontem. 

Segundo os consultores da Infor, há um job que lê os dados atualizados do GNFe e atualiza o status da nota no Ln.

Qualquer dúvida, me avise.

Grato, Humberto.

**Comment by rosanaprignolato** [comment]
OK, Obrigada!
