### ISSUE TITLE
NIKE - VW_NK_FAT_FATURAMENTO

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#444]
Humberto,

Analisando os dados da NIKE pela tela do LN, sessão "cislil504m00l - Nota Fiscal", identificamos que as referências Fiscais "F00000044", "F00000045" e "F00000046" possuem o Status da NF-e como Processada e a situação da NF como Lançado e Impresso, respectivamente. Esses status contemplam a leitura dos dados dessas referências pela view de faturamento, porém a mesma não está trazendo nenhuma informação. Abaixo segue a imagem das telas que pesquisamos:

![image](https://cloud.githubusercontent.com/assets/7606062/9060400/c785565c-3a89-11e5-9028-ee19499a794f.png)

Detalhando a "F00000044":

![image](https://cloud.githubusercontent.com/assets/7606062/9060411/ecea975e-3a89-11e5-8f80-883988e7debc.png)

Detalhando a "F00000045":

![image](https://cloud.githubusercontent.com/assets/7606062/9060443/4e3e7a66-3a8a-11e5-980d-a646f6433483.png)

Detalhando a "F00000046":

![image](https://cloud.githubusercontent.com/assets/7606062/9060457/7462861a-3a8a-11e5-86ca-3579f75255d2.png)

Você poderia analisar a view para identificar e corrigir o problema?

Obrigada
Rosana

**Comment by hkasai** [comment]
Rosana,

Estas notas são de venda sem pedido, que não movimentam estoque, e não deveriam aparecer mesmo na query. Foram testes realizados pelo pessoal do Fiscal. Este tipo de nota não existirá em Produção.

Há uma condição na query que só lista as notas encontradas na tabela "cisli245". Há uma sessão de consulta para esta tabela, o código é a "cisli2540m000".

Qualquer dúvida, me avise.

Grato, Humberto.

**Comment by rosanaprignolato** [comment]
ok, obrigada!
