### ISSUE TITLE
VW_NK_PEV_DET - Duplicidade de informações

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#446]
Humberto,

A view em questão está trazendo 3 registros para a entrega "180016001", conforme o select apresentado abaixo:

![image](https://cloud.githubusercontent.com/assets/7606062/9176191/5c764bec-3f60-11e5-9c96-88ab31ca386d.png)

Analisando os dados pelo LN, temos em Pedidos Integrados o seguinte (3 pçs x R$ 49,90):

![image](https://cloud.githubusercontent.com/assets/7606062/9176418/9e03cd2c-3f61-11e5-93db-11ec96450410.png)

e na sessão de Ordem de Vendas, temos essa venda desmembrada em 2 linhas:

![image](https://cloud.githubusercontent.com/assets/7606062/9176473/f262e72c-3f61-11e5-976d-48b4baef6764.png)

É uma única venda de 3 peças e a view está retornando como se fosse a venda de 6 peças. Você poderia verificar o que está errado nesta view?

Essa entrega é referente à mesma Referência Fiscal que o Marcus reportou anteriormente com problemas no Faturamento

Obrigada
Rosana

**Comment by hkasai** [comment]
Rosana,

A query foi corrigida, agrupando-se as linhas da tabela "znsls401" em uma única linha, para a mesma entrega e mesmo item.

Qualquer dúvida, me avise.

Grato, Humberto.

**Comment by rosanaprignolato** [comment]
Ok Humberto, já fiz a substituição da view e agora os dados estão corretos.
