### ISSUE TITLE
NIKE - stg_pev_cab

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#456]
Humberto,

Na carga de hoje da NIKE (24/09/2015), identificamos um problema com o NR_ENTREGA do pedido "1800378" que foi devolvido. A entrega '180037803' está trazendo dois registros, pois o NR_ENTREGA_CANCELADO é distinto (180037801, 180037802).

Como utilizamos o NR_ENTREGA como chave, a carga acaba apresentando problemas. No Barateiro temos números de entregas distintos para esses casos. 

Você poderia verificar isso?

**Comment by hkasai** [comment]
Rosana,

Não podemos enviar este pedido para a Nike, pois está com erro. O "Tipo de Pedido" na venda está como "N" e na devolução  "O", gerando as duas ordens de venda de devolução. O Tipo "O" é usado normalmente para Venda Triangular (Fatura e Remessa).

Os registros vieram com erro do Front.

Qualquer dúvida, me avise.

Grato, Humberto.

**Comment by rosanaprignolato** [comment]
Humberto,

Além da entrega que você me informou estar com erro do Front, encontrei mais 2 registros na carga de hoje. Poderia me informar se é o mesmo problema?

Os registros são:

![image](https://cloud.githubusercontent.com/assets/7606062/10134025/eba6b8be-65b8-11e5-8123-8aaa6fc4040f.png)

Obrigada!

**Comment by rosanaprignolato** [comment]
Humberto, por favor, retirar dessa view os campos SQ_PEDIDO_CANCELADO e NR_ENTREGA_CANCELADO. Vamos incluir esses campos na VW_NK_PEV_DET.

Obrigada

**Comment by hkasai** [comment]
Rosana,

Os campos foram excluídos da query.

Grato, Humberto.

**Comment by rosanaprignolato** [comment]
Ok Humberto, já efetivei as alterações. Obrigada
