### ISSUE TITLE
NIKE - stg_pev_det

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#457]
Humberto, por favor, incluir nesta view os campos SQ_PEDIDO_CANCELADO e NR_ENTREGA_CANCELADO. 

Obrigada

**Comment by hkasai** [comment]
Rosana,

Os campos foram incluídos na query.

Grato, Humberto.

**Comment by rosanaprignolato** [comment]
Ok Humberto, já efetivei as alterações. Obrigada!
