### ISSUE TITLE
VW_NK_FAT_FATURAMENTO

### ISSUE THREAD

**Issue by marcusmsv** [marcusmsv/Nova#459]
Humberto,

Poderia incluir um case na view de Faturamento da Nike de: 

Quando o tipo da NF seja Fatura/Remessa, na linha da nota NF de Fatura, o CD_TRANSPORTADORA ser carregado com os dados da NF de Remessa. 

Hoje, o campo retorna vazio nos casos das notas de fatura.

Procedimento de utilizar os dados de remessa na fatura é utilizado nas views de integração do Rodrigo.

Obrigado.

**Comment by hkasai** [comment]
Marcus,

A query foi corrigida e atualizada no Git.

Grato, Humberto.

**Comment by marcusmsv** [comment]
Humberto,

Poderia verificar os casos que estão com CD_TRANSPORTADORA = ' '.

Obrigado.
