### ISSUE TITLE
VW_DOM_SKU_KIT -  Campo CD_ITEM

### ISSUE THREAD

**Issue by rosanaprignolato** [marcusmsv/Nova#461]
Humberto,

Estou retomando a extração dos dados do ambiente de homologação da Nova e reparei que o campo CD_ITEM está trazendo dados alfanuméricos. Isso é correto? Veja abaixo alguns registros que a view está retornando:

![image](https://cloud.githubusercontent.com/assets/7606062/11245303/33ce7bbe-8df9-11e5-9d82-fbfca5ab7386.png)

Obrigada

**Comment by hkasai** [comment]
Rosana,

O código do item do Ln é alfanumérico, e alguns tipos de item estão parametrizados com letras. O item agrupador da Nike é um exemplo, começa com 'A'.

Grato, Humberto.

**Comment by rosanaprignolato** [comment]
Ok Humberto, analisando pela tela do LN notamos que estes itens estão com a descrição como "Teste". Para podermos trazer os dados agora, consideramos somente os itens que são numéricos. Segundo o Marcus, na carga de produção do Barateiro, os itens são numéricos.
